version: '3'
services:
    api:
        build: .
        depends_on:
            - postgres
        ports: 
            # - <port on localhost>:<port on container>
            - 8000:8000
        volumes:
            - ./:/usr/src/app:"ro" # we can ad ":ro" so that nothing can be edited from container itself, only from the original source sysem 
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        
        # env_file:    #### pointing to environment variables in the existing files
        #     ./.env
        environment:   # listing env variables one by one
            - DATABASE_HOSTNAME=postgres # it's the same name as our DB service section
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=fastapi_db
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=9e87c05b5d5d3fbc6d044cface0bae28e67f1432993fc8cd939952e1e88dee37
            - ALGORITHM=HS256 
            - ACCESS_TOKEN_EXPIRE_MINUTES=60


        
    
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=fastapi_db
            
        volumes:
          - postgres-db:/var/lib/postgresql/data


volumes:
    postgres-db:
  